name: Sample workflow using golang-security-action

# on: [push, pull_request]
on: [push]

jobs:
    golang-security-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ynniss/golang-security-action@master
              with:
                CODE_PATH: "./src/"
